import Foundation
import Testing
@testable import SureWord

/// One vector as `tests/fixtures/assistant-markdown-corpus.json` stores it.
/// `streaming` applies to `stripFollowUpMarkers` and `normalizeAssistantMarkdown`
/// only, exactly as in the vitest suites.
struct AssistantMarkdownVector: Decodable, Sendable, CustomTestStringConvertible {
    let name: String
    let fn: String
    let input: String
    let expected: String
    let why: String?
    let streaming: Bool?

    var testDescription: String { name }
}

/// The corpus is read straight out of the repo relative to `#filePath` rather
/// than copied into the test bundle: it is generated by
/// `tests/fixtures/gen-assistant-markdown-corpus.mjs` and looped over by BOTH
/// vitest suites, and a copy is a copy that drifts.
struct AssistantMarkdownCorpus: Decodable, Sendable {
    struct PartVector: Decodable, Sendable {
        let name: String
        let parts: [String]
        let expected: String
    }

    struct Message: Decodable, Sendable {
        let id: String
        let quirks: [String]
        let content: String
    }

    struct Synthetic: Decodable, Sendable {
        let name: String
        let input: String
    }

    let vectors: [AssistantMarkdownVector]
    let partVectors: [PartVector]
    let messages: [Message]
    let synthetic: [Synthetic]

    /// `<repo>/macos/SureWordTests/<this file>` → `<repo>/tests/fixtures/…`.
    static let url: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("tests")
        .appendingPathComponent("fixtures")
        .appendingPathComponent("assistant-markdown-corpus.json")

    /// Loaded once, with the failure KEPT rather than swallowed. A `try?` here
    /// turned a missing or malformed corpus into an empty one, and an empty
    /// corpus turns eight tests into no-ops that all report green - the exact
    /// failure mode this suite exists to prevent.
    private static let loaded: (corpus: AssistantMarkdownCorpus, failure: String?) = load()

    static var shared: AssistantMarkdownCorpus { loaded.corpus }
    static var loadFailure: String? { loaded.failure }

    private static func load() -> (AssistantMarkdownCorpus, String?) {
        let empty = AssistantMarkdownCorpus(
            vectors: [], partVectors: [], messages: [], synthetic: []
        )
        do {
            let data = try Data(contentsOf: url)
            return (try JSONDecoder().decode(AssistantMarkdownCorpus.self, from: data), nil)
        } catch {
            return (empty, "\(url.path): \(error)")
        }
    }
}

// MARK: - Helpers

/// Swift's `==` on `String` compares by canonical equivalence, which would let
/// a normalizer that swapped a precomposed character for its decomposed form
/// pass. The corpus is byte-level truth, so compare scalars.
private func exactlyEqual(_ lhs: String, _ rhs: String) -> Bool {
    Array(lhs.unicodeScalars) == Array(rhs.unicodeScalars)
}

private func runVector(_ vector: AssistantMarkdownVector) -> String {
    let streaming = vector.streaming == true
    switch vector.fn {
    case "closeOpenInlineMarkdown":
        return AssistantMarkdown.closeOpenInlineMarkdown(vector.input)
    case "normalizeAssistantMarkdown":
        return AssistantMarkdown.normalize(vector.input, streaming: streaming)
    case "normalizeInlineHtml":
        return AssistantMarkdown.normalizeInlineHtml(vector.input)
    case "repairMarkdownBlocks":
        return AssistantMarkdown.repairMarkdownBlocks(vector.input)
    case "stripFollowUpMarkers":
        return AssistantMarkdown.stripFollowUpMarkers(vector.input, streaming: streaming)
    default:
        return "<<unknown function \(vector.fn)>>"
    }
}

/// Lines, counted the way markdown counts them. A lone CR is a line break to
/// every parser, so a helper that split on "\n" alone saw a CR-delimited
/// document as one line.
private func markdownLines(_ text: String) -> [[Unicode.Scalar]] {
    var lines: [[Unicode.Scalar]] = []
    var current: [Unicode.Scalar] = []
    let scalars = Array(text.unicodeScalars)
    var index = 0
    while index < scalars.count {
        if scalars[index] == "\r" {
            lines.append(current)
            current = []
            index += (index + 1 < scalars.count && scalars[index + 1] == "\n") ? 2 : 1
            continue
        }
        if scalars[index] == "\n" {
            lines.append(current)
            current = []
            index += 1
            continue
        }
        current.append(scalars[index])
        index += 1
    }
    lines.append(current)
    return lines
}

private func isBlankScalarLine(_ line: [Unicode.Scalar]) -> Bool {
    line.allSatisfy { Character($0).isWhitespace }
}

/// Number of maximal runs of consecutive blockquote lines (`/^ {0,3}>/`).
private func blockquoteRuns(_ text: String) -> Int {
    var runs = 0
    var inRun = false
    for line in markdownLines(text) {
        var index = 0
        while index < line.count, index < 3, line[index] == " " { index += 1 }
        let isQuote = index < line.count && line[index] == ">"
        if isQuote, !inRun { runs += 1 }
        inRun = isQuote
    }
    return runs
}

/// Lines a GFM table would read as a row. A row is a single line by definition,
/// so any rule that turns one line into two invents a row with the wrong column
/// count - which is exactly what a `<br>` hard break used to do.
private func tableRows(_ text: String) -> Int {
    var rows = 0
    for line in markdownLines(text) {
        let trimmed = line.drop { Character($0).isWhitespace }
        if trimmed.first == "|" { rows += 1 }
    }
    return rows
}

/// The lines inside every fenced code block, delimiters excluded, exactly as
/// written. Deliberately a SECOND, independent implementation of the module's
/// fence scan - blockquote prefixes, indent up to a nested container, matching
/// marker character and run length, and a quoted fence ending with its quote.
/// If the module and this helper ever disagree, one of them is wrong.
private func fencedLines(_ text: String) -> String {
    struct Open {
        var depth: Int
        var character: Unicode.Scalar
        var length: Int
    }
    var kept: [String] = []
    var open: Open?

    for line in markdownLines(text) {
        var prefixEnd = 0
        var depth = 0
        var lastMarker = -1
        while prefixEnd < line.count {
            let scalar = line[prefixEnd]
            if scalar == " " || scalar == "\t" {
                prefixEnd += 1
            } else if scalar == ">" {
                depth += 1
                lastMarker = prefixEnd
                prefixEnd += 1
            } else {
                break
            }
        }
        var indent = 0
        for index in (lastMarker + 1)..<prefixEnd {
            indent += line[index] == "\t" ? 4 : 1
        }

        if let current = open, current.depth > 0,
           isBlankScalarLine(line) || depth < current.depth {
            open = nil
        }

        var run: (character: Unicode.Scalar, length: Int, infoIsBlank: Bool)?
        if indent <= 12, prefixEnd < line.count {
            let character = line[prefixEnd]
            if character == "`" || character == "~" {
                var end = prefixEnd
                while end < line.count, line[end] == character { end += 1 }
                if end - prefixEnd >= 3 {
                    run = (
                        character,
                        end - prefixEnd,
                        line[end...].allSatisfy { Character($0).isWhitespace }
                    )
                }
            }
        }

        let rendered = String(String.UnicodeScalarView(line))
        guard let run else {
            if open != nil { kept.append(rendered) }
            continue
        }
        if open == nil {
            open = Open(depth: depth, character: run.character, length: run.length)
        } else if let current = open,
                  depth == current.depth,
                  run.character == current.character,
                  run.length >= current.length,
                  run.infoIsBlank {
            open = nil
        } else {
            kept.append(rendered)
        }
    }
    return kept.joined(separator: "\n")
}

/// Up to `count` cut points spread evenly across a string of `length`.
private func cutPositions(_ length: Int, _ count: Int) -> [Int] {
    if length <= count { return Array(0...max(length, 0)) }
    var positions: [Int] = []
    for index in 0..<count {
        positions.append(Int((Double(index) * Double(length) / Double(count - 1)).rounded()))
    }
    return positions
}

// MARK: - Suite

/// The macOS/iOS port of `src/utils/assistantMarkdown.ts`, pinned to the same
/// shared corpus the web (`tests/assistant-markdown.test.mjs`) and Android
/// (`mobile/src/lib/assistantMarkdown.test.ts`) suites loop over.
@Suite("AssistantMarkdown")
struct AssistantMarkdownTests {
    private let corpus = AssistantMarkdownCorpus.shared

    @Test("Fixture is present and covers every repaired construct")
    func fixtureIsPresent() {
        if let failure = AssistantMarkdownCorpus.loadFailure {
            Issue.record(
                """
                the shared corpus could not be read, so every corpus-driven test \
                below silently ran zero vectors: \(failure)
                """
            )
        }
        #expect(corpus.vectors.count >= 90, "vector table shrank unexpectedly")
        #expect(corpus.messages.count >= 8, "production corpus shrank unexpectedly")
        #expect(corpus.partVectors.count >= 4)
        #expect(!corpus.synthetic.isEmpty)
        for marker in ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "B1", "B2", "B3", "B4"] {
            #expect(
                corpus.vectors.contains { $0.name.hasPrefix(marker) },
                "no vectors for \(marker)"
            )
        }
    }

    @Test("Corpus vector", arguments: AssistantMarkdownCorpus.shared.vectors)
    func vector(_ vector: AssistantMarkdownVector) {
        let actual = runVector(vector)
        #expect(
            exactlyEqual(actual, vector.expected),
            """
            \(vector.name)
            why: \(vector.why ?? "-")
            expected: \(vector.expected.debugDescription)
            actual:   \(actual.debugDescription)
            """
        )
    }

    @Test("joinAssistantTextParts")
    func joinTextParts() {
        for vector in corpus.partVectors {
            #expect(
                exactlyEqual(AssistantMarkdown.joinTextParts(vector.parts), vector.expected),
                "\(vector.name)"
            )
        }
    }

    /// A combining scalar or a variation selector directly after a marker fuses
    /// with it into ONE Swift `Character`, and that cluster equals neither `*`
    /// nor `>` nor `` ` ``. While this port indexed lines by `Character` every
    /// marker test below missed the marker and the port diverged from the TS -
    /// a literal `**` left on screen mid-stream, a blockquote that never became
    /// a card. Expected values are the TS's own output, taken by running
    /// `src/utils/assistantMarkdown.ts` under `node --experimental-strip-types`.
    @Test("Markers followed by a combining scalar are still markers")
    func combiningScalarAfterMarker() {
        let cases: [(name: String, actual: String, expected: String)] = [
            (
                "** + VS16 + keycap, streaming",
                AssistantMarkdown.normalize("Step **\u{FE0F}\u{20E3} one", streaming: true),
                "Step **\u{FE0F}\u{20E3} one**"
            ),
            (
                "** + VS16 + keycap, closeOpenInlineMarkdown",
                AssistantMarkdown.closeOpenInlineMarkdown("Step **\u{FE0F}\u{20E3} one"),
                "Step **\u{FE0F}\u{20E3} one**"
            ),
            (
                "> + combining acute opens a blockquote",
                AssistantMarkdown.normalize("Text\n>\u{0301} quoted", streaming: false),
                "Text\n\n>\u{0301} quoted"
            ),
            (
                "> + combining acute, repairMarkdownBlocks",
                AssistantMarkdown.repairMarkdownBlocks("Text\n>\u{0301} quoted"),
                "Text\n\n>\u{0301} quoted"
            ),
            (
                "backtick + combining acute, streaming",
                AssistantMarkdown.normalize("Run `\u{0301}code here", streaming: true),
                "Run `\u{0301}code here`"
            ),
            (
                "~~ + VS16, streaming",
                AssistantMarkdown.normalize("Say ~~\u{FE0F}gone", streaming: true),
                "Say ~~\u{FE0F}gone~~"
            ),
        ]
        for entry in cases {
            #expect(
                exactlyEqual(entry.actual, entry.expected),
                """
                \(entry.name)
                expected: \(entry.expected.debugDescription)
                actual:   \(entry.actual.debugDescription)
                """
            )
        }
    }

    @Test("Block repair preserves the blockquote run count of every vector")
    func blockquoteRunsPerVector() {
        for vector in corpus.vectors
        where vector.fn == "repairMarkdownBlocks" || vector.fn == "normalizeAssistantMarkdown" {
            #expect(
                blockquoteRuns(runVector(vector)) == blockquoteRuns(vector.input),
                "\(vector.name): a blockquote was split or merged"
            )
        }
    }

    @Test("No pipeline stage rewrites the contents of a fenced code block")
    func fencedCodeIsNeverRewritten() {
        for vector in corpus.vectors {
            #expect(
                exactlyEqual(fencedLines(runVector(vector)), fencedLines(vector.input)),
                "\(vector.name): fenced code was rewritten"
            )
        }
        for message in corpus.messages {
            for streaming in [false, true] {
                #expect(
                    exactlyEqual(
                        fencedLines(AssistantMarkdown.normalize(message.content, streaming: streaming)),
                        fencedLines(message.content)
                    ),
                    "\(message.id) streaming=\(streaming)"
                )
            }
        }
    }

    @Test("No vector gains or loses a GFM table row")
    func tableRowsPerVector() {
        for vector in corpus.vectors {
            #expect(
                tableRows(runVector(vector)) == tableRows(vector.input),
                "\(vector.name): a table row was split or merged"
            )
        }
    }

    @Test("Production messages keep their table rows and blockquote runs")
    func productionInvariants() {
        for message in corpus.messages {
            let normalized = AssistantMarkdown.normalize(message.content, streaming: false)
            #expect(tableRows(normalized) == tableRows(message.content), "\(message.id)")
            #expect(
                blockquoteRuns(normalized) == blockquoteRuns(message.content),
                "\(message.id) (\(message.quirks.joined(separator: ", ")))"
            )
            #expect(!normalized.unicodeScalars.contains("\r"), "\(message.id) carries a stray carriage return")
            let fenceCount: (String) -> Int = { text in
                markdownLines(text).filter { line in
                    var index = 0
                    while index < line.count, index < 3, line[index] == " " { index += 1 }
                    guard index < line.count else { return false }
                    let character = line[index]
                    guard character == "`" || character == "~" else { return false }
                    var end = index
                    while end < line.count, line[end] == character { end += 1 }
                    return end - index >= 3
                }.count
            }
            #expect(fenceCount(normalized) == fenceCount(message.content), "\(message.id)")
        }
    }

    @Test("normalize is idempotent over every corpus entry")
    func idempotence() {
        for message in corpus.messages {
            for streaming in [false, true] {
                let once = AssistantMarkdown.normalize(message.content, streaming: streaming)
                let twice = AssistantMarkdown.normalize(once, streaming: streaming)
                #expect(exactlyEqual(twice, once), "\(message.id) streaming=\(streaming)")
            }
        }
        for vector in corpus.vectors {
            for streaming in [false, true] {
                let once = AssistantMarkdown.normalize(vector.input, streaming: streaming)
                let twice = AssistantMarkdown.normalize(once, streaming: streaming)
                #expect(exactlyEqual(twice, once), "\(vector.name) streaming=\(streaming)")
            }
        }
    }

    @Test("Every prefix of every corpus entry survives being rendered mid-stream")
    func streamCutSweep() {
        // A streamed answer is rendered at every intermediate length, so a rule
        // that only holds for whole messages is a rule that breaks on screen.
        // The normalizer must never turn one blockquote into two, never split a
        // table row, and must be a fixed point at every cut.
        var entries: [(String, [Unicode.Scalar])] = []
        entries += corpus.vectors.map { ($0.name, Array($0.input.unicodeScalars)) }
        entries += corpus.messages.map { ($0.id, Array($0.content.unicodeScalars)) }
        entries += corpus.synthetic.map { ($0.name, Array($0.input.unicodeScalars)) }

        var checked = 0
        for (name, scalars) in entries {
            for cut in cutPositions(scalars.count, 200) {
                let prefix = String(String.UnicodeScalarView(scalars[0..<cut]))
                for streaming in [true, false] {
                    let context = "\(name) cut=\(cut) streaming=\(streaming)"
                    let once = AssistantMarkdown.normalize(prefix, streaming: streaming)
                    #expect(
                        blockquoteRuns(once) <= blockquoteRuns(prefix),
                        "\(context): a blockquote was split"
                    )
                    #expect(tableRows(once) <= tableRows(prefix), "\(context): a table row was split")
                    #expect(
                        exactlyEqual(AssistantMarkdown.normalize(once, streaming: streaming), once),
                        "\(context): not a fixed point"
                    )
                    checked += 1
                }
            }
        }
        #expect(checked > 5000, "sweep covered only \(checked) prefixes")
    }
}
