import Foundation

/// The "Start a note" templates (PRD E1): a port of
/// `mobile/src/features/notes/noteTemplates.ts`, whose payloads are identical
/// on web and Android. `NoteTemplatesTests` asserts this produces the same
/// title, Tiptap JSON, HTML, plain text and word count as the TS
/// implementation, byte for byte, from fixtures generated by running it.
///
/// No user content is parsed as HTML: the only interpolated value is the
/// church name, escaped like every other block.
enum NoteTemplates {
    enum ID: String, CaseIterable, Identifiable, Sendable {
        case verseStudy = "verse-study"
        case sermon
        case prayer
        case blank

        var id: String { rawValue }
    }

    struct Option: Identifiable, Sendable {
        let id: ID
        let label: String
        let description: String
    }

    static let options: [Option] = [
        Option(id: .verseStudy, label: "Verse study", description: "One verse, what I learn, and how I obey."),
        Option(id: .sermon, label: "Sermon notes", description: "Sunday's date, my church, and what I need to remember."),
        Option(id: .prayer, label: "Prayer journal", description: "My thanks, requests, and the people I pray for."),
        Option(id: .blank, label: "Blank note", description: "Start from an empty page."),
    ]

    /// What `POST /api/notes` is created with. Field names match the Android
    /// seed (`html` is sent as `htmlContent`).
    struct Seed: Equatable, Sendable {
        var title: String
        var content: String
        var html: String
        var plainText: String
        var wordCount: Int
    }

    private enum Kind { case heading, prompt, quote }
    private struct Block {
        let kind: Kind
        let text: String
    }

    private static func heading(_ text: String) -> Block { Block(kind: .heading, text: text) }
    private static func prompt(_ text: String) -> Block { Block(kind: .prompt, text: text) }
    private static func quote(_ text: String) -> Block { Block(kind: .quote, text: text) }

    /// `nil` for Blank, which creates an ordinary "Untitled Note".
    /// `calendar` is the device's (`toLocaleDateString` uses local time); the
    /// tests pin it to UTC to match fixtures generated with `TZ=UTC`.
    static func build(
        _ id: ID,
        churchName: String? = nil,
        now: Date = Date(),
        calendar: Calendar = .current
    ) -> Seed? {
        if id == .blank { return nil }
        var day = now
        if id == .sermon {
            // Back to this week's Sunday (`now.getDate() - now.getDay()`).
            let weekday = calendar.component(.weekday, from: now) - 1
            day = calendar.date(byAdding: .day, value: -weekday, to: now) ?? now
        }
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US")
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.dateFormat = "EEEE, MMMM d, yyyy"
        let date = formatter.string(from: day)

        let title: String
        switch id {
        case .sermon: title = "Sermon notes: \(date)"
        case .prayer: title = "Prayer journal: \(date)"
        default: title = "Verse study"
        }
        let church = churchName?.trimmingCharacters(in: .whitespacesAndNewlines)

        let blocks: [Block]
        switch id {
        case .verseStudy:
            blocks = [
                heading("I begin with God's words"), quote("I copy the full verse here and record its reference (KJV)."),
                heading("I attend to what the verse says"), prompt("I describe what the verse says in its context."),
                heading("I let Scripture explain Scripture"), prompt("I record related passages and what they teach me."),
                heading("I receive what God teaches me"), prompt("I name what I learn about God and what I must change."),
                heading("What I do next"), prompt("I choose one concrete act of obedience today."),
            ]
        case .sermon:
            blocks = (church.map { $0.isEmpty ? [] : [prompt("My church: \($0)")] } ?? []) + [
                heading("I begin with the preached passage"), quote("I copy the sermon passage and record its reference (KJV)."),
                heading("I keep the truth the preacher explained"), prompt("I state the sermon's central claim in my own words."),
                heading("I remember what Scripture showed me"), prompt("I record the supporting passages and the truth I need to remember."),
                heading("What I do next"), prompt("I name how I will obey what I heard this week."),
            ]
        default:
            blocks = [
                heading("I thank God for His mercies"), prompt("I name the mercies I have received."),
                heading("I bring my requests to God"), prompt("I state what I ask and entrust the outcome to Him."),
                heading("I pray for these people"), prompt("I name each person and what I ask for them."),
                heading("What I do next"), prompt("I name how I will remain faithful while I wait."),
            ]
        }

        let html = blocks.map { block in
            let safe = escapeHTML(block.text)
            switch block.kind {
            case .heading: return "<h2>\(safe)</h2>"
            case .quote: return "<blockquote><p>\(safe)</p></blockquote>"
            case .prompt: return "<p><em>\(safe)</em></p>"
            }
        }.joined()

        // Hand-written so the key order and escaping match `JSON.stringify`
        // exactly; the server stores this string as-is.
        let nodes = blocks.map { block -> String in
            let marks = block.kind == .prompt ? #","marks":[{"type":"italic"}]"# : ""
            let leaf = #"{"type":"text","text":\#(jsonString(block.text))\#(marks)}"#
            switch block.kind {
            case .heading: return #"{"type":"heading","attrs":{"level":2},"content":[\#(leaf)]}"#
            case .quote: return #"{"type":"blockquote","content":[{"type":"paragraph","content":[\#(leaf)]}]}"#
            case .prompt: return #"{"type":"paragraph","content":[\#(leaf)]}"#
            }
        }
        let content = #"{"type":"doc","content":[\#(nodes.joined(separator: ","))]}"#
        let plainText = blocks.map(\.text).joined(separator: "\n\n")
        let wordCount = NoteMarkdownExport.jsTrim(plainText)
            .split(whereSeparator: { $0.isWhitespace })
            .count
        return Seed(title: title, content: content, html: html, plainText: plainText, wordCount: wordCount)
    }

    private static func escapeHTML(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }

    /// `JSON.stringify` of a string: quotes, backslashes and control
    /// characters escaped, everything else (including non-ASCII) verbatim.
    static func jsonString(_ text: String) -> String {
        var output = "\""
        for scalar in text.unicodeScalars {
            switch scalar {
            case "\"": output += "\\\""
            case "\\": output += "\\\\"
            case "\n": output += "\\n"
            case "\r": output += "\\r"
            case "\t": output += "\\t"
            case "\u{08}": output += "\\b"
            case "\u{0C}": output += "\\f"
            default:
                if scalar.value < 0x20 || (0xD800...0xDFFF).contains(scalar.value) {
                    output += String(format: "\\u%04x", scalar.value)
                } else {
                    output.unicodeScalars.append(scalar)
                }
            }
        }
        return output + "\""
    }
}
