import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
	ActivityIndicator,
	FlatList,
	Image,
	Modal,
	Pressable,
	Share,
	StyleSheet,
	Text as ScriptureText,
	View,
	type ListRenderItemInfo,
} from "react-native";
import { AppText as Text } from "@/components/AppText";
import { typography } from "@/theme";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as Clipboard from "expo-clipboard";
import { Ionicons } from "@expo/vector-icons";
import { GlassCard, Screen } from "@/components/ui";
import { useTabBarSpace } from "@/features/chat/layout";
import {
	parseTranslationId,
	readerTranslation,
	saveVerseToNote,
} from "@/features/chat/verseActions";
import { BottomSheet } from "@/features/notes/components/primitives";
import { useStableGetToken } from "@/features/notes/useStableGetToken";
import { apiJson } from "@/lib/api";
import { parseCard } from "@/features/learn/learn";
import { useReadingLogStatus } from "@/features/reading/readingLogStore";
import { useReaderTracking } from "@/features/reading/useReaderTracking";
import { bookByOrder, type Book } from "@/features/bible/books";
import { HIGHLIGHT_PRESETS, highlightWash } from "@/features/bible/highlights";
import { highlightLabelFor } from "@/features/settings/preferences";
import {
	removeHighlight,
	setHighlight,
	useChapterHighlights,
} from "@/features/bible/highlightsStore";
import { TRANSLATIONS, getChapter, type TranslationId } from "@/features/bible/translations";
import { bibleVersePlainText } from "@/features/bible/verseMarkup";
import { getBsbChapter } from "@/features/bible/bsb";
import { readerVerseSegments, readerSectionHeadings } from "@/features/bible/redLetters";
import { HighlightColorPicker } from "@/features/bible/HighlightColorPicker";
import { useVerseInsight } from "@/features/bible/useVerseInsight";
import { VerseInsightSection } from "@/features/bible/VerseInsightSection";
import { WordStudySection } from "@/features/bible/WordStudySection";
import {
	CrossReferencesSection,
	type CrossReferenceTarget,
} from "@/features/bible/CrossReferencesSection";
import {
	MAX_SELECTED_VERSES,
	selectionColor,
	selectionCount,
	selectionIncludes,
	selectionReference,
	selectionShareText,
	selectionText,
	selectionVerses,
	toggleVerse,
	type VerseSelection,
} from "@/features/bible/verseSelection";
import { VerseSheet, type VerseSheetTier } from "@/features/bible/verse-sheet/VerseSheet";
import { VerseActionBar, type VerseAction } from "@/features/bible/verse-sheet/VerseActionBar";
import { StudyTabs } from "@/features/bible/verse-sheet/StudyTabs";
import { InsightTeaser } from "@/features/bible/verse-sheet/InsightTeaser";
import { fonts, radius, spacing, type Colors } from "@/theme";
import {
	setBibleTranslation,
	useHighlightLabels,
	useSettings,
	useThemedStyles,
	useTheme,
} from "@/features/settings/settingsStore";

const FONT_STEPS = [17, 20, 24, 28] as const;
// The reader's page surface: photoreal aged parchment (light) and a dark
// leather-toned sheet (dark), generated by scripts/generate-parchment.mjs.
// Metro needs static require paths, so both ship and the theme picks one.
const PARCHMENT_LIGHT = require("../../../assets/parchment-light.webp");
const PARCHMENT_DARK = require("../../../assets/parchment-dark.webp");
const HIGHLIGHT_MS = 2400;
/** Remembered for the whole app session, like the old reader's default. */
let sessionFontStep = 1;

type StudyTabKey = "explain" | "words" | "seealso";
const STUDY_TABS: { key: StudyTabKey; label: string }[] = [
	{ key: "explain", label: "Explain" },
	{ key: "words", label: "Words" },
	{ key: "seealso", label: "See also" },
];
/** A quick second tap grows the range; wait for the reader to settle before asking the model. */
const SELECTION_SETTLE_MS = 350;
/** Longer than the sheet's slide-out, so what it shows does not vanish mid-slide. */
const SHEET_CLOSE_MS = 320;

type ChapterStyles = ReturnType<typeof createStyles>;

interface VerseRowProps {
	bookOrder: number;
	chapterNumber: number;
	translation: TranslationId;
	redLetterColor: string;
	/** The verse as the provider gave it - KJV plain text, NKJV inline markup. */
	markup: string;
	verseNumber: number;
	/** Stored highlight color for this verse, if any. */
	verseColor: string | undefined;
	/** True only for the verse a ?verse= deep link is briefly flashing. */
	flashed: boolean;
	/** Part of the verse sheet's current selection. */
	selected: boolean;
	parchment: boolean;
	fontSize: number;
	lineHeight: number;
	styles: ChapterStyles;
	colors: Colors;
	onPress: (verseNumber: number) => void;
}

/**
 * One verse row. Memoized on primitives plus the identity-stable themed
 * `styles`/`colors`, because tapping a verse streams its explanation into this
 * same screen: every token is a state write here, and without the memo each one
 * would re-render and re-parse every mounted verse of the chapter.
 */
const VerseRow = React.memo(function VerseRow({
	bookOrder,
	chapterNumber,
	translation,
	redLetterColor,
	markup,
	verseNumber,
	verseColor,
	flashed,
	selected,
	parchment,
	fontSize,
	lineHeight,
	styles,
	colors,
	onPress,
}: VerseRowProps) {
	const segments = useMemo(
		() => readerVerseSegments(markup, translation, bookOrder, chapterNumber, verseNumber),
		[markup, translation, bookOrder, chapterNumber, verseNumber],
	);
	const open = useCallback(() => onPress(verseNumber), [onPress, verseNumber]);

	const formatted =
		translation === "BSB" ? getBsbChapter(bookOrder, chapterNumber)[verseNumber - 1] : null;
	return (
		<View>
			{readerSectionHeadings(translation, bookOrder, chapterNumber, verseNumber).map((heading, index) => (
				<Text key={`${index}:${heading}`} accessibilityRole="header" style={styles.sectionHeading}>
					{heading}
				</Text>
			))}
			<Pressable
				accessibilityRole="button"
				accessibilityState={{ selected }}
				delayLongPress={300}
				onPress={open}
				onLongPress={open}
				style={[
					styles.verseRow,
					// The selection wash and the deep-link flash share one look: both
					// say "this is the verse we mean". The flash comes last so it wins.
					(selected || flashed) &&
						(parchment ? styles.verseRowHighlighted : { backgroundColor: colors.accentSoft }),
				]}
			>
				<ScriptureText
					style={[styles.verseText, !parchment && { color: colors.text }, { fontSize, lineHeight }]}
				>
					<ScriptureText
						style={[
							styles.verseNumber,
							!parchment && { color: colors.textMuted },
							selected && { color: colors.accent },
						]}
					>
						{verseNumber}
						{"\u2002"}
					</ScriptureText>
					{formatted?.omitted ? (
						<ScriptureText style={styles.omittedVerse}>
							Not included in this edition’s main text.
						</ScriptureText>
					) : null}
					{segments.map((segment, segmentIndex) => (
						<ScriptureText
							key={`${segmentIndex}:${segment.italic ? "i" : "r"}`}
							style={[
								segment.italic ? styles.verseItalic : undefined,
								segment.jesusSpeech ? { color: redLetterColor } : undefined,
								verseColor ? { backgroundColor: highlightWash(verseColor) } : undefined,
							]}
						>
							{segment.text}
						</ScriptureText>
					))}
				</ScriptureText>
			</Pressable>
		</View>
	);
});

/**
 * Chapter reading screen: bundled KJV (offline) or NKJV (bolls.life), verse
 * long-press actions (copy/share/save/Ask AI), adjustable type size, and
 * prev/next navigation that rolls into adjacent books like YouVersion.
 */
export default function BibleChapterScreen() {
	const router = useRouter();
	const readingStatus = useReadingLogStatus();
	const getToken = useStableGetToken();
	const tabBarSpace = useTabBarSpace();
	const styles = useThemedStyles(createStyles);
	const { colors, isDark } = useTheme();
	const params = useLocalSearchParams<{
		book?: string;
		chapter?: string;
		verse?: string;
		/** Source translation from a retrieved-verse deep link; local only. */
		translation?: string;
	}>();

	// The params ARE what the reader shows — they must never be copied into
	// state. `bible` is a nested stack that keeps this screen mounted, so a
	// second deep link from chat reuses the instance and only updates the
	// params; anything seeded once at mount would keep rendering the first
	// chapter forever. Mirrors src/components/bible/ChapterReader.tsx on web.
	const order = Number.parseInt(typeof params.book === "string" ? params.book : "1", 10);
	const chapter = Number.parseInt(typeof params.chapter === "string" ? params.chapter : "1", 10);
	const verseParam =
		Number.parseInt(typeof params.verse === "string" ? params.verse : "", 10) || null;

	const book: Book | null = bookByOrder(order);
	// A retrieved verse carries its source translation in the route so Read opens
	// the matching text. Keep that override local: opening a source card must not
	// silently change the account-wide default in Settings. Tapping a chip is an
	// explicit preference choice, so it clears the route override and persists it.
	const sourceTranslationParam = parseTranslationId(params.translation);
	const { translation: accountTranslation, parchment } = useSettings();
	const highlightLabels = useHighlightLabels();
	const translation = readerTranslation(accountTranslation, params.translation);
	const setTranslation = useCallback(
		(next: TranslationId) => {
			if (sourceTranslationParam) router.setParams({ translation: undefined });
			setBibleTranslation(next);
		},
		[router, sourceTranslationParam],
	);
	const [verses, setVerses] = useState<string[]>([]);
	// Which chapter `verses` actually holds. Params change a render before the
	// new text arrives, so without this the effects below would run once against
	// the previous chapter's verses while `order`/`chapter` already point at the
	// new one.
	const [loadedKey, setLoadedKey] = useState<string | null>(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [readerOptionsVisible, setReaderOptionsVisible] = useState(false);
	const [fontStep, setFontStep] = useState(sessionFontStep);
	const [highlighted, setHighlighted] = useState<number | null>(null);
	// The verse sheet's selection: one verse, or a range grown by tapping more
	// verses while the sheet is open. Null means the sheet is closed.
	const [selection, setSelection] = useState<VerseSelection | null>(null);
	// The last non-null selection keeps the sheet's content stable while it
	// animates closed; the sheet itself is driven by `selection !== null`.
	const [shownSelection, setShownSelection] = useState<VerseSelection>({ start: 1, end: 1 });
	const [sheetTier, setSheetTier] = useState<VerseSheetTier>("peek");
	const [studyTab, setStudyTab] = useState<StudyTabKey>("explain");
	const [copied, setCopied] = useState(false);
	const [saveBusy, setSaveBusy] = useState(false);
	const [learnStatus, setLearnStatus] = useState<"idle" | "adding" | "added">("idle");
	const [actionMessage, setActionMessage] = useState<{
		text: string;
		tone: "muted" | "danger";
	} | null>(null);
	const {
		status: insightStatus,
		text: insightText,
		error: insightError,
		start: startInsight,
		reset: resetInsight,
	} = useVerseInsight(getToken);

	const listRef = useRef<FlatList<string>>(null);
	const lastFlashed = useRef<string | null>(null);
	const requestId = useRef(0);
	const copiedTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

	const chapterKey = `${translation}:${order}:${chapter}`;
	// Stored highlight colors for the chapter on screen: `Map<verse, #RRGGBB>`.
	// Backed by the shared store (AsyncStorage cache + per-chapter server GET).
	const highlights = useChapterHighlights(translation, order, chapter);
	const [pickerVisible, setPickerVisible] = useState(false);

	const load = useCallback(async () => {
		// Paging quickly, or deep-linking while a fetch is in flight, can leave
		// two loads racing; only the newest may write. NKJV comes over the network,
		// so the slower one is not always the older one.
		const id = ++requestId.current;
		const key = `${translation}:${order}:${chapter}`;
		setLoading(true);
		setError(null);
		try {
			const next = await getChapter(translation, order, chapter);
			if (requestId.current !== id) return;
			setVerses(next);
			setLoadedKey(key);
		} catch (err) {
			if (requestId.current !== id) return;
			setVerses([]);
			setLoadedKey(null);
			setError(err instanceof Error ? err.message : "That chapter could not be loaded.");
		} finally {
			if (requestId.current === id) setLoading(false);
		}
	}, [translation, order, chapter]);

	useEffect(() => {
		void load();
	}, [load]);

	// A newly opened chapter starts at the top; the ?verse= effect below scrolls
	// on from there. Needed because the reused screen keeps the previous
	// chapter's scroll offset.
	useEffect(() => {
		listRef.current?.scrollToOffset({ offset: 0, animated: false });
	}, [translation, order, chapter]);

	// ?verse= deep link: scroll to the verse once the chapter is on screen and
	// flash it briefly so the eye lands there. Guarded by the reference it last
	// flashed rather than a one-shot flag, so every new deep link re-arms it —
	// and gated on loadedKey, or the stale-verses render would burn that guard
	// on the incoming reference before its text was ever on screen.
	useEffect(() => {
		if (loading || error || loadedKey !== chapterKey || !verses.length) return;
		if (!verseParam || verseParam < 1 || verseParam > verses.length) return;
		const flashKey = `${chapterKey}:${verseParam}`;
		if (lastFlashed.current === flashKey) return;
		lastFlashed.current = flashKey;
		const scrollTimer = setTimeout(() => {
			listRef.current?.scrollToIndex({
				index: verseParam - 1,
				viewPosition: 0.15,
				animated: false,
			});
			setHighlighted(verseParam);
		}, 250);
		const clearTimer = setTimeout(() => setHighlighted(null), 250 + HIGHLIGHT_MS);
		return () => {
			clearTimeout(scrollTimer);
			clearTimeout(clearTimer);
		};
	}, [loading, error, loadedKey, chapterKey, verses, verseParam]);

	const readingTracking = useReaderTracking({
		book: order,
		chapter,
		translation,
		verseCount: verses.length,
		ready: !loading && !error && loadedKey === chapterKey && !!book,
		// The peek leaves most of the chapter readable; only the expanded study
		// view covers the text.
		obscured:
			(selection !== null && sheetTier === "expanded") || pickerVisible || readerOptionsVisible,
	});

	const stepFont = useCallback((delta: number) => {
		setFontStep((step) => {
			const next = Math.min(FONT_STEPS.length - 1, Math.max(0, step + delta));
			sessionFontStep = next;
			return next;
		});
	}, []);

	const neighbors = useMemo(() => {
		const current = bookByOrder(order);
		if (!current) return { prev: null, next: null };
		const at = (o: number, c: number) => ({ order: o, chapter: c });
		const prevBook = bookByOrder(order - 1);
		const nextBook = bookByOrder(order + 1);
		return {
			prev:
				chapter > 1
					? at(order, chapter - 1)
					: prevBook
						? at(prevBook.order, prevBook.chapters)
						: null,
			next:
				chapter < current.chapters
					? at(order, chapter + 1)
					: nextBook
						? at(nextBook.order, 1)
						: null,
		};
	}, [order, chapter]);

	const goTo = useCallback(
		(target: { order: number; chapter: number } | null) => {
			if (!target) return;
			// setParams rather than local state, so params stay the one description
			// of what is on screen. Clearing ?verse= stops the flash effect from
			// firing again in the chapter we just paged into, and forgetting the
			// last flash lets a later deep link back to that same verse re-flash it.
			lastFlashed.current = null;
			router.setParams({
				book: String(target.order),
				chapter: String(target.chapter),
				verse: "",
			});
		},
		[router],
	);

	const reference = book ? `${book.name} ${chapter}` : "";

	// Every verse without markup, once per chapter load. The sheet, clipboard,
	// share, note and Ask AI all read the selection from here, and a range
	// covers verses that were never tapped themselves.
	const plainTexts = useMemo(
		() =>
			verses.map((markup, index) =>
				readerVerseSegments(markup, translation, order, chapter, index + 1)
					.map((segment) => segment.text)
					.join(""),
			),
		[verses, translation, order, chapter],
	);

	const sheetOpen = selection !== null;
	const activeSelection = selection ?? shownSelection;
	const selectionRef = book ? selectionReference(book.name, chapter, activeSelection) : "";
	const selectionPlain = selectionText(plainTexts, activeSelection);
	const selectedCount = selectionCount(activeSelection);
	const selectionHex = selectionColor(highlights, activeSelection);
	const selectionHasColor = selectionVerses(activeSelection).some((verse) => highlights.has(verse));
	const selectionPreset = selectionHex
		? HIGHLIGHT_PRESETS.find(
				(preset) => preset.color.toLowerCase() === selectionHex.toLowerCase(),
			)
		: undefined;
	const selectionHighlightLabel = highlightLabelFor(highlightLabels, selectionPreset?.name);

	// The insight is not reset here: the teaser must keep its text while the
	// sheet slides out. The close effect below aborts it once the slide is done.
	const closeSheet = useCallback(() => {
		setSelection(null);
		setCopied(false);
		setActionMessage(null);
	}, []);

	// The sheet is not a modal, so a cross-reference can navigate straight
	// away: nothing has to be dismissed first.
	const openCrossReference = useCallback(
		(target: CrossReferenceTarget) => {
			closeSheet();
			router.push({
				pathname: "/bible/chapter",
				params: {
					book: String(target.order),
					chapter: String(target.chapter),
					...(target.verse !== undefined ? { verse: String(target.verse) } : {}),
					translation,
				},
			});
		},
		[closeSheet, router, translation],
	);

	// Tap-a-verse: a selection immediately starts streaming a short AI
	// explanation (cached per reference for the session). The first tap asks
	// at once; a tap that grows the range waits a beat in case another follows.
	const previousSelection = useRef<VerseSelection | null>(null);
	useEffect(() => {
		const wasOpen = previousSelection.current !== null;
		previousSelection.current = selection;
		if (!selection || !book) return;
		const request = () =>
			startInsight({
				reference: selectionReference(book.name, chapter, selection),
				text: selectionText(plainTexts, selection),
				translation,
			});
		if (!wasOpen) {
			request();
			return;
		}
		const timer = setTimeout(request, SELECTION_SETTLE_MS);
		return () => clearTimeout(timer);
	}, [selection, book, chapter, plainTexts, translation, startInsight]);

	const retryInsight = useCallback(() => {
		if (!selection) return;
		startInsight({ reference: selectionRef, text: selectionPlain, translation });
	}, [selection, selectionRef, selectionPlain, startInsight, translation]);

	const askAI = useCallback(
		(verse: { reference: string; text: string }) => {
			closeSheet();
			router.push({
				pathname: "/",
				params: {
					attachRef: verse.reference,
					attachText: verse.text,
					attachTranslation: translation,
				},
			});
		},
		[router, closeSheet, translation],
	);

	// The Words tab's two buttons: both prefill the composer, but only a
	// question about this verse pins the passage. A search across the whole
	// Bible would be narrowed by an attachment, so it goes without one.
	const askAboutWord = useCallback(
		(prompt: string, attach: boolean) => {
			closeSheet();
			router.push({
				pathname: "/",
				params: {
					prompt,
					...(attach
						? {
								attachRef: selectionRef,
								attachText: selectionPlain,
								attachTranslation: translation,
							}
						: {}),
				},
			});
		},
		[router, closeSheet, selectionRef, selectionPlain, translation],
	);

	useEffect(
		() => () => {
			if (copiedTimer.current) clearTimeout(copiedTimer.current);
		},
		[],
	);

	const onCopyVerse = useCallback(async () => {
		if (!selection) return;
		await Clipboard.setStringAsync(selectionShareText(selectionRef, selectionPlain, translation));
		setCopied(true);
		if (copiedTimer.current) clearTimeout(copiedTimer.current);
		copiedTimer.current = setTimeout(() => setCopied(false), 1400);
	}, [selection, selectionRef, selectionPlain, translation]);

	const onShareVerse = useCallback(() => {
		if (!selection) return;
		Share.share({
			message: selectionShareText(selectionRef, selectionPlain, translation),
		}).catch(() => {});
	}, [selection, selectionRef, selectionPlain, translation]);

	const onSaveVerse = useCallback(async () => {
		if (!selection || saveBusy) return;
		setSaveBusy(true);
		setActionMessage(null);
		try {
			const noteId = await saveVerseToNote(
				getToken,
				{ reference: selectionRef, text: selectionPlain },
				translation,
			);
			closeSheet();
			router.push({ pathname: "/notes/[id]", params: { id: noteId } });
		} catch {
			setActionMessage({
				text: "The note could not be saved. Check your connection and try again.",
				tone: "danger",
			});
		} finally {
			setSaveBusy(false);
		}
	}, [selection, saveBusy, selectionRef, selectionPlain, getToken, translation, router, closeSheet]);

	// Learn takes one verse per request, so a range is added verse by verse;
	// the route is idempotent, so a retry after a mid-way failure is safe.
	const onLearn = useCallback(async () => {
		if (!selection) return;
		if (learnStatus === "added") {
			router.push("/(app)/bible/learn");
			return;
		}
		if (learnStatus === "adding") return;
		setLearnStatus("adding");
		setActionMessage(null);
		const source = selectionHex ? "highlight" : "sheet";
		try {
			for (const verse of selectionVerses(selection)) {
				const card = parseCard(
					await apiJson(getToken, "/api/learn", {
						method: "POST",
						body: { book: order, chapter, verse, translation, source },
					}),
				);
				if (card.book !== order || card.chapter !== chapter || card.verse !== verse) {
					throw new Error("Unexpected verse");
				}
			}
			setLearnStatus("added");
			setActionMessage({
				text: selectedCount === 1 ? "Added to Learn." : `Added ${selectedCount} verses to Learn.`,
				tone: "muted",
			});
		} catch {
			setLearnStatus("idle");
			setActionMessage({
				text: "Could not add to Learn. Check your connection and try again.",
				tone: "danger",
			});
		}
	}, [selection, learnStatus, router, selectionHex, getToken, order, chapter, translation, selectedCount]);

	// Highlight writes are optimistic - the verse rows recolor immediately and
	// the store rolls back any verse whose PUT/DELETE fails, so the sheet just
	// fires one write per selected verse.
	const applyHighlight = useCallback(
		(color: string) => {
			if (!selection) return;
			for (const verse of selectionVerses(selection)) {
				setHighlight(getToken, { translation, book: order, chapter, verse, color }).catch(
					() => {},
				);
			}
		},
		[selection, getToken, translation, order, chapter],
	);

	const onRemoveHighlight = useCallback(() => {
		if (!selection) return;
		for (const verse of selectionVerses(selection)) {
			removeHighlight(getToken, { translation, book: order, chapter, verse }).catch(() => {});
		}
	}, [selection, getToken, translation, order, chapter]);

	const fontSize = FONT_STEPS[fontStep];
	const lineHeight = Math.round(fontSize * 1.8);

	// Keeps VerseRow's onPress identity stable while the insight streams: the
	// toggle reads the current selection through a ref, not a closure.
	const selectionNow = useRef(selection);
	selectionNow.current = selection;
	const onVersePress = useCallback((verseNumber: number) => {
		const current = selectionNow.current;
		const next = toggleVerse(current, verseNumber);
		if (next === current) {
			// The only way the toggle leaves the selection alone is the cap.
			setActionMessage({ text: `Up to ${MAX_SELECTED_VERSES} verses at a time.`, tone: "muted" });
			return;
		}
		// Written now, not on the next render, so two taps in one frame chain.
		selectionNow.current = next;
		if (next) setShownSelection(next);
		if (!current && next) {
			// A fresh open starts at the peek on Explain with clean action state.
			setSheetTier("peek");
			setStudyTab("explain");
		}
		// A grown or re-anchored range is a different thing to copy or learn.
		setCopied(false);
		setLearnStatus("idle");
		setActionMessage(null);
		setSelection(next);
	}, []);

	// Chapter or translation change while the sheet is open: the selection no
	// longer describes what is on screen.
	useEffect(() => {
		setSelection(null);
		resetInsight();
	}, [chapterKey, resetInsight]);

	// Closing the sheet abandons the insight once the slide-out has finished
	// (the sheet keeps its content while it leaves); leaving the screen does too.
	useEffect(() => {
		if (sheetOpen) return;
		const timer = setTimeout(resetInsight, SHEET_CLOSE_MS);
		return () => clearTimeout(timer);
	}, [sheetOpen, resetInsight]);

	const openStudy = useCallback((tab: StudyTabKey) => {
		setStudyTab(tab);
		setSheetTier("expanded");
	}, []);

	const sheetActions = useMemo<VerseAction[]>(
		() => [
			{
				key: "ask",
				icon: "sparkles-outline",
				label: "Ask",
				onPress: () => askAI({ reference: selectionRef, text: selectionPlain }),
			},
			{
				key: "copy",
				icon: copied ? "checkmark" : "copy-outline",
				label: copied ? "Copied" : "Copy",
				active: copied,
				onPress: () => void onCopyVerse(),
			},
			{ key: "share", icon: "share-outline", label: "Share", onPress: onShareVerse },
			{
				key: "note",
				icon: "create-outline",
				label: saveBusy ? "Saving…" : "Note",
				disabled: saveBusy,
				onPress: () => void onSaveVerse(),
			},
			{
				key: "learn",
				icon: learnStatus === "added" ? "school" : "school-outline",
				label: learnStatus === "adding" ? "Adding…" : learnStatus === "added" ? "Added" : "Learn",
				active: learnStatus === "added",
				disabled: learnStatus === "adding",
				onPress: () => void onLearn(),
			},
		],
		[askAI, selectionRef, selectionPlain, copied, onCopyVerse, onShareVerse, saveBusy, onSaveVerse, learnStatus, onLearn],
	);

	const barMessage = actionMessage
		? actionMessage
		: selectionHighlightLabel
			? { text: `Marked as “${selectionHighlightLabel}”`, tone: "muted" as const }
			: null;

	const renderVerse = useCallback(
		({ item, index }: ListRenderItemInfo<string>) => (
			<VerseRow
				markup={item}
				bookOrder={order}
				chapterNumber={chapter}
				translation={translation}
				redLetterColor={isDark ? "#EF8A83" : "#A12E2A"}
				verseNumber={index + 1}
				verseColor={highlights.get(index + 1)}
				flashed={highlighted === index + 1}
				selected={selectionIncludes(selection, index + 1)}
				parchment={parchment}
				fontSize={fontSize}
				lineHeight={lineHeight}
				styles={styles}
				colors={colors}
				onPress={onVersePress}
			/>
		),
		[
			highlights,
			highlighted,
			selection,
			parchment,
			fontSize,
			lineHeight,
			styles,
			colors,
			onVersePress,
			order,
			chapter,
			translation,
			isDark,
		],
	);

	if (!book) {
		return (
			<Screen>
				<View style={styles.topBar}>
					<Pressable
						accessibilityRole="button"
						accessibilityLabel="Back to chapters"
						onPress={() => router.back()}
						style={styles.fontButton}
					>
						<Ionicons name="chevron-back" size={24} color={colors.text} />
					</Pressable>
				</View>
				<View style={styles.center}>
					<Text style={styles.loadingLabel}>That book could not be found.</Text>
				</View>
			</Screen>
		);
	}

	return (
		<Screen style={{ backgroundColor: isDark ? "#121212" : "#FAF9F6" }}>
			<View style={styles.topBar}>
				<Pressable
					accessibilityRole="button"
					accessibilityLabel="Back to chapters"
					onPress={() => router.back()}
					style={styles.fontButton}
				>
					<Ionicons name="chevron-back" size={24} color={colors.text} />
				</Pressable>
				<View style={styles.headerSpacer} />
				<Pressable
					accessibilityRole="button"
					accessibilityLabel={`Translation and reading settings, ${translation}`}
					onPress={() => setReaderOptionsVisible(true)}
					style={styles.translationChip}
				>
					<Ionicons name="globe-outline" size={18} color={colors.text} />
					<Text style={styles.translationChipLabel}>{translation}</Text>
					<Ionicons name="chevron-down" size={14} color={colors.textMuted} />
				</Pressable>
				<Pressable
					accessibilityRole="button"
					accessibilityLabel="Reading settings"
					onPress={() => setReaderOptionsVisible(true)}
					style={styles.fontButton}
				>
					<Ionicons name="text-outline" size={22} color={colors.text} />
				</Pressable>
			</View>
			<BottomSheet
				visible={readerOptionsVisible}
				onClose={() => setReaderOptionsVisible(false)}
				title="Reading settings"
			>
				<Text style={styles.optionsLabel}>Text size & chapter people</Text>
				<View style={styles.fontControls}>
					<Pressable
						accessibilityRole="button"
						accessibilityLabel="Who's in this chapter"
						onPress={() => {
							setReaderOptionsVisible(false);
							router.push({
								pathname: "/bible/timeline",
								params: { book: String(order), chapter: String(chapter) },
							});
						}}
						style={styles.fontButton}
					>
						<Ionicons name="people-outline" size={15} color={colors.textSecondary} />
					</Pressable>
					<Pressable
						accessibilityRole="button"
						accessibilityLabel="Decrease text size"
						disabled={fontStep === 0}
						onPress={() => stepFont(-1)}
						style={[styles.fontButton, fontStep === 0 && { opacity: 0.35 }]}
					>
						<Text style={styles.fontButtonLabel}>A−</Text>
					</Pressable>
					<Pressable
						accessibilityRole="button"
						accessibilityLabel="Increase text size"
						disabled={fontStep === FONT_STEPS.length - 1}
						onPress={() => stepFont(1)}
						style={[styles.fontButton, fontStep === FONT_STEPS.length - 1 && { opacity: 0.35 }]}
					>
						<Text style={[styles.fontButtonLabel, { ...typography.body }]}>A+</Text>
					</Pressable>
				</View>
				<Text style={styles.optionsLabel}>Translation</Text>
				<View style={styles.translationRow}>
					{(Object.keys(TRANSLATIONS) as TranslationId[]).map((id) => (
						<Pressable
							key={id}
							accessibilityRole="button"
							accessibilityState={{ selected: translation === id }}
							onPress={() => setTranslation(id)}
							style={[styles.translationChip, translation === id && styles.translationChipActive]}
						>
							<Text
								style={[styles.translationChipLabel, translation === id && { color: colors.text }]}
							>
								{id}
							</Text>
						</Pressable>
					))}
				</View>
				<Text style={styles.optionsLabel}>
					{translation === "KJV"
						? "KJV words of Jesus · eBible edition. Editorial headings · BSB."
						: translation === "BSB"
							? "Section headings and words of Jesus · Berean Standard Bible"
							: "Red letters aren't available from our NKJV text provider yet."}
				</Text>
			</BottomSheet>

			{readingStatus.error ? (
				<Pressable
					accessibilityRole="button"
					onPress={() => router.push("/bible/history")}
					style={{ paddingHorizontal: spacing.lg, paddingBottom: spacing.sm }}
				>
					<Text accessibilityRole="alert" style={{ color: colors.danger, ...typography.support }}>
						{readingStatus.error} Open reading log →
					</Text>
				</Pressable>
			) : null}

			{loading ? (
				<View style={styles.center}>
					<ActivityIndicator color={colors.accent} />
					<Text style={styles.loadingLabel}>
						{translation === "NKJV" ? "Loading the NKJV…" : "Opening the chapter…"}
					</Text>
				</View>
			) : error ? (
				<View style={styles.center}>
					<GlassCard style={styles.errorCard}>
						<Text style={styles.errorText}>{error}</Text>
						<Pressable accessibilityRole="button" onPress={() => void load()} style={styles.retry}>
							<Text style={styles.retryLabel}>Try again</Text>
						</Pressable>
					</GlassCard>
				</View>
			) : (
				<View style={styles.body}>
					{parchment && (
						<Image
							source={isDark ? PARCHMENT_DARK : PARCHMENT_LIGHT}
							style={styles.paper}
							resizeMode="cover"
							accessible={false}
						/>
					)}
					<FlatList
						key={chapterKey}
						{...readingTracking}
						ref={listRef}
						style={styles.readerList}
						data={verses}
						keyExtractor={(_, index) => String(index + 1)}
						ListHeaderComponent={
							readerSectionHeadings(translation, order, chapter, 1).length > 0 ? null : (
								<Text accessibilityRole="header" style={styles.chapterHeading}>
									{reference}
								</Text>
							)
						}
						contentContainerStyle={[styles.content, { paddingBottom: spacing.xxl }]}
						onScrollToIndexFailed={({ index }) => {
							// Rows have variable height; approximate, then retry once laid out.
							listRef.current?.scrollToOffset({
								offset: index * 48,
								animated: false,
							});
							setTimeout(
								() =>
									listRef.current?.scrollToIndex({
										index,
										viewPosition: 0.15,
										animated: false,
									}),
								250,
							);
						}}
						ListFooterComponent={
							<View>
								<Text
									style={[styles.copyright, !parchment && { color: colors.textGhost, opacity: 1 }]}
								>
									{TRANSLATIONS[translation].label} — {TRANSLATIONS[translation].copyright}
								</Text>
							</View>
						}
						renderItem={renderVerse}
					/>
					<View style={[styles.readerDock, { marginBottom: tabBarSpace }]}>
						<View style={styles.chapterNavigator}>
							<Pressable
								accessibilityRole="button"
								accessibilityLabel="Previous chapter"
								disabled={!neighbors.prev}
								onPress={() => goTo(neighbors.prev)}
								style={[styles.dockArrow, !neighbors.prev && { opacity: 0.3 }]}
							>
								<Ionicons name="chevron-back" size={24} color={colors.text} />
							</Pressable>
							<Pressable
								accessibilityRole="button"
								accessibilityLabel={`Choose chapter, ${reference}`}
								onPress={() =>
									router.push({ pathname: "/bible/chapters", params: { book: String(order) } })
								}
								style={styles.chapterPicker}
							>
								<Text numberOfLines={1} style={styles.chapterLabel}>
									{reference}
								</Text>
								<Ionicons name="chevron-down" size={14} color={colors.textMuted} />
							</Pressable>
							<Pressable
								accessibilityRole="button"
								accessibilityLabel="Next chapter"
								disabled={!neighbors.next}
								onPress={() => goTo(neighbors.next)}
								style={[styles.dockArrow, !neighbors.next && { opacity: 0.3 }]}
							>
								<Ionicons name="chevron-forward" size={24} color={colors.text} />
							</Pressable>
						</View>
						<Pressable
							accessibilityRole="button"
							accessibilityLabel={`Ask AI about ${reference}`}
							onPress={() =>
								askAI({
									reference,
									text: verses
										.map((text, index) => `${index + 1} ${bibleVersePlainText(text)}`)
										.join("\n"),
								})
							}
							style={styles.dockAI}
						>
							<Ionicons name="sparkles-outline" size={21} color={colors.text} />
							<Text style={styles.dockAILabel}>Ask AI</Text>
						</Pressable>
					</View>
					{/* Tap-a-verse. Non-modal and anchored above the tab bar: the peek
					    keeps the chapter readable and tappable so a second tap grows the
					    selection; dragging up opens the study view. */}
					<VerseSheet
						open={sheetOpen}
						tier={sheetTier}
						onTierChange={setSheetTier}
						onClose={closeSheet}
						title={selectionRef}
						subtitle={selectedCount > 1 ? `${selectedCount} verses` : undefined}
						bottomOffset={tabBarSpace}
						peek={
							<InsightTeaser
								status={insightStatus}
								text={insightText}
								error={insightError}
								onPress={() => openStudy("explain")}
								onRetry={retryInsight}
							/>
						}
						footer={
							<VerseActionBar
								color={selectionHex}
								canRemove={selectionHasColor}
								onHighlight={applyHighlight}
								onRemoveHighlight={onRemoveHighlight}
								onCustomColor={() => setPickerVisible(true)}
								labelForPreset={(name) => highlightLabelFor(highlightLabels, name) ?? name}
								actions={sheetActions}
								message={barMessage?.text}
								messageTone={barMessage?.tone}
							/>
						}
					>
						<Text numberOfLines={4} style={styles.studyQuote}>
							{selectionPlain}
						</Text>
						<StudyTabs
							tabs={STUDY_TABS}
							value={studyTab}
							onChange={(key) => setStudyTab(key as StudyTabKey)}
						/>
						<View style={styles.studyBody}>
							{studyTab === "explain" ? (
								<VerseInsightSection
									status={insightStatus}
									text={insightText}
									error={insightError}
									onRetry={retryInsight}
								/>
							) : studyTab === "words" ? (
								// Each study is a model generation, so a range studies its
								// first verse only (as See also does) rather than firing one
								// per selected verse.
								<>
									{selectedCount > 1 ? (
										<Text style={styles.studyNote}>For verse {activeSelection.start}</Text>
									) : null}
									<WordStudySection
										key={activeSelection.start}
										getToken={getToken}
										book={order}
										chapter={chapter}
										verse={sheetOpen ? activeSelection.start : null}
										onAsk={askAboutWord}
									/>
								</>
							) : (
								<>
									{selectedCount > 1 ? (
										<Text style={styles.studyNote}>For verse {activeSelection.start}</Text>
									) : null}
									<CrossReferencesSection
										key={`${activeSelection.start}:${translation}`}
										reference={
											book
												? selectionReference(book.name, chapter, {
														start: activeSelection.start,
														end: activeSelection.start,
													})
												: ""
										}
										translation={translation}
										enabled={sheetOpen}
										onNavigate={openCrossReference}
										alwaysExpanded
									/>
								</>
							)}
						</View>
					</VerseSheet>
				</View>
			)}

			{/* The verse sheet lives inside the reader body (see the render above): it is not a modal, so the chapter stays tappable to grow the selection. */}
			{/* Custom highlight color. Rendered as a sibling Modal so it stacks
			    above the verse sheet; a gesture completion applies the color. */}
			<Modal
				visible={pickerVisible}
				transparent
				animationType="fade"
				statusBarTranslucent
				onRequestClose={() => setPickerVisible(false)}
			>
				<Pressable
					style={styles.pickerBackdrop}
					onPress={() => setPickerVisible(false)}
					accessibilityLabel="Close color picker"
				/>
				<View style={styles.pickerCard} pointerEvents="box-none">
					<View style={styles.pickerCardInner}>
						<Text style={styles.pickerTitle}>Custom color</Text>
						{pickerVisible ? (
							<HighlightColorPicker
								value={selectionHex ?? HIGHLIGHT_PRESETS[0].color}
								onComplete={(hex) => {
									applyHighlight(hex);
									setPickerVisible(false);
								}}
								style={styles.picker}
							/>
						) : null}
					</View>
				</View>
			</Modal>
		</Screen>
	);
}

const createStyles = (c: Colors) =>
	StyleSheet.create({
		topBar: {
			flexDirection: "row",
			alignItems: "center",
			gap: spacing.md,
			paddingHorizontal: spacing.lg,
			paddingVertical: spacing.md,
		},
		back: { color: c.accent, ...typography.control, fontWeight: "600" },
		title: {
			flex: 1,
			color: c.text,
			...typography.screenTitle,
			fontWeight: "600",
			textAlign: "center",
		},
		fontControls: { flexDirection: "row", gap: spacing.sm },
		translationRow: {
			flexDirection: "row",
			justifyContent: "flex-start",
			gap: 8,
			paddingHorizontal: spacing.lg,
			paddingBottom: spacing.sm,
		},
		translationChip: {
			flexDirection: "row",
			alignItems: "center",
			gap: 6,
			minHeight: 44,
			borderRadius: radius.full,
			borderWidth: StyleSheet.hairlineWidth,
			borderColor: c.borderStrong,
			backgroundColor: c.surface,
			paddingHorizontal: spacing.sm,
			paddingVertical: 4,
		},
		translationChipActive: {
			borderColor: c.textMuted,
			backgroundColor: c.surfacePressed,
		},
		translationChipLabel: {
			color: c.textMuted,
			...typography.micro,
			fontWeight: "700",
		},
		center: {
			flex: 1,
			alignItems: "center",
			justifyContent: "center",
			padding: spacing.xl,
		},
		loadingLabel: {
			marginTop: spacing.md,
			color: c.textFaint,
			...typography.support,
		},
		errorCard: { padding: spacing.xl, alignItems: "center", gap: spacing.md },
		errorText: {
			color: c.textSecondary,
			...typography.support,
			textAlign: "center",
		},
		retry: {
			borderRadius: radius.md,
			backgroundColor: c.accentSoft,
			borderColor: c.accentBorder,
			borderWidth: 1,
			paddingHorizontal: spacing.xl,
			paddingVertical: spacing.sm,
		},
		retryLabel: { color: c.accent, ...typography.control, fontWeight: "600" },
		body: { flex: 1 },
		// The page itself: fixed parchment the verses scroll over, like text
		// moving across an unrolled scroll under a lamp.
		paper: {
			position: "absolute",
			top: 0,
			right: 0,
			bottom: 0,
			left: 0,
			width: undefined,
			height: undefined,
		},
		readerList: { flex: 1 },
		headerSpacer: { flex: 1 },
		optionsLabel: {
			color: c.textMuted,
			...typography.support,
			marginTop: spacing.lg,
			marginBottom: spacing.sm,
		},
		sectionHeading: {
			fontFamily: fonts.verseItalic,
			fontSize: 24,
			lineHeight: 34,
			color: c.text,
			marginTop: 16,
			marginBottom: 20,
		},
		omittedVerse: { color: c.textMuted, fontSize: 14, fontStyle: "italic" },
		chapterHeading: {
			fontFamily: fonts.verseItalic,
			fontSize: 28,
			lineHeight: 38,
			color: c.text,
			marginBottom: 28,
		},
		content: {
			paddingHorizontal: 28,
			paddingTop: 24,
			width: "100%",
			maxWidth: 720,
			alignSelf: "center",
		},
		readerDock: {
			flexDirection: "row",
			alignItems: "center",
			gap: 12,
			paddingHorizontal: 20,
			paddingVertical: 12,
			borderTopWidth: StyleSheet.hairlineWidth,
			borderTopColor: c.borderStrong,
		},
		chapterNavigator: {
			flex: 1,
			flexDirection: "row",
			alignItems: "center",
			backgroundColor: c.surfacePressed,
			borderRadius: radius.full,
			minHeight: 52,
		},
		dockArrow: {
			width: 44,
			minHeight: 52,
			alignItems: "center",
			justifyContent: "center",
		},
		chapterPicker: {
			flex: 1,
			minHeight: 52,
			flexDirection: "row",
			gap: 6,
			alignItems: "center",
			justifyContent: "center",
		},
		chapterLabel: {
			flexShrink: 1,
			color: c.text,
			...typography.control,
			fontWeight: "700",
		},
		dockAI: {
			minWidth: 52,
			minHeight: 52,
			alignItems: "center",
			justifyContent: "center",
			gap: 2,
		},
		dockAILabel: { color: c.textMuted, ...typography.micro },
		verseRow: { borderRadius: 4 },
		verseRowHighlighted: { backgroundColor: c.parchmentHighlight },
		verseText: {
			color: c.parchmentInk,
			fontFamily: fonts.verse,
			marginBottom: 16,
		},
		verseItalic: { fontFamily: fonts.verseItalic },
		verseNumber: {
			color: c.parchmentNumber,
			fontSize: 12,
			fontFamily: "System",
			fontWeight: "400",
		},
		copyright: {
			marginTop: spacing.lg,
			color: c.parchmentInk,
			opacity: 0.55,
			...typography.micro,
			textAlign: "center",
			fontStyle: "italic",
		},
		studyQuote: {
			color: c.textSecondary,
			fontFamily: fonts.verse,
			...typography.chat,
			paddingHorizontal: spacing.lg,
			paddingBottom: spacing.md,
		},
		studyBody: { paddingHorizontal: spacing.md, paddingTop: spacing.md, paddingBottom: spacing.lg },
		studyNote: {
			color: c.textFaint,
			...typography.meta,
			paddingHorizontal: spacing.sm,
			paddingBottom: spacing.sm,
		},
		fontButton: {
			minWidth: 44,
			minHeight: 44,
			alignItems: "center",
			justifyContent: "center",
			borderRadius: radius.md,
			borderWidth: StyleSheet.hairlineWidth,
			borderColor: c.borderStrong,
			backgroundColor: c.surface,
			paddingHorizontal: spacing.sm,
			paddingVertical: 4,
		},
		fontButtonLabel: {
			color: c.textSecondary,
			...typography.control,
			fontWeight: "700",
		},
		pickerBackdrop: {
			position: "absolute",
			top: 0,
			right: 0,
			bottom: 0,
			left: 0,
			backgroundColor: "rgba(0,0,0,0.72)",
		},
		pickerCard: {
			flex: 1,
			alignItems: "center",
			justifyContent: "center",
			padding: spacing.xl,
		},
		pickerCardInner: {
			alignSelf: "stretch",
			borderRadius: radius.xl,
			borderWidth: StyleSheet.hairlineWidth,
			borderColor: c.borderStrong,
			backgroundColor: c.bgElevated,
			padding: spacing.lg,
		},
		pickerTitle: {
			color: c.text,
			...typography.control,
			fontWeight: "600",
			marginBottom: spacing.md,
			textAlign: "center",
		},
		picker: { width: "100%", gap: spacing.md },
	});
