import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
	closeOpenInlineMarkdown,
	joinAssistantTextParts,
	normalizeAssistantMarkdown,
	normalizeInlineHtml,
	repairMarkdownBlocks,
	stripFollowUpMarkers,
} from "../src/utils/assistantMarkdown.ts";

// This file is deliberately ASCII-only. Every vector that needs an em dash, a
// bullet glyph or Greek/Hebrew lives in the JSON fixture, which is generated by
// tests/fixtures/gen-assistant-markdown-corpus.mjs (run it to add or change a
// vector; it self-checks against the real module): the editing tooling on this
// machine silently rewrites U+2014 to an ASCII hyphen, and a vector mangled
// that way passes for the wrong reason. The generated
// tests/fixtures/assistant-markdown-corpus.json is the single source of truth
// for the vectors, and mobile/src/lib/assistantMarkdown.test.ts loops over the
// very same file, so the web and Android copies cannot drift.

const FIXTURE = fileURLToPath(
	new URL("./fixtures/assistant-markdown-corpus.json", import.meta.url)
);
const corpus = JSON.parse(readFileSync(FIXTURE, "utf8"));

const FUNCTIONS = {
	closeOpenInlineMarkdown,
	normalizeAssistantMarkdown,
	normalizeInlineHtml,
	repairMarkdownBlocks,
	stripFollowUpMarkers,
};

const TAKES_OPTIONS = new Set(["stripFollowUpMarkers", "normalizeAssistantMarkdown"]);

function runVector(vector) {
	const fn = FUNCTIONS[vector.fn];
	assert.ok(fn, `unknown function in fixture: ${vector.fn}`);
	return TAKES_OPTIONS.has(vector.fn)
		? fn(vector.input, { streaming: vector.streaming === true })
		: fn(vector.input);
}

/** Up to `count` cut points spread evenly across a string of `length`. */
function cutPositions(length, count) {
	if (length <= count) {
		const all = [];
		for (let index = 0; index <= length; index += 1) all.push(index);
		return all;
	}
	const positions = [];
	for (let index = 0; index < count; index += 1) {
		positions.push(Math.round((index * length) / (count - 1)));
	}
	return positions;
}

/**
 * Lines, counted the way markdown counts them. A lone CR is a line break to
 * every parser and to JS's own /m anchors, so a helper that split on "\n" alone
 * saw a CR-delimited document as one line and scored its invariants against a
 * shape no renderer ever sees.
 */
function lines(text) {
	return text.replace(/\r\n?/g, "\n").split("\n");
}

/** Number of maximal runs of consecutive blockquote lines. */
function blockquoteRuns(text) {
	let runs = 0;
	let inRun = false;
	for (const line of lines(text)) {
		const isQuote = /^ {0,3}>/.test(line);
		if (isQuote && !inRun) runs += 1;
		inRun = isQuote;
	}
	return runs;
}

/**
 * Lines that a GFM table would read as a row. A table row is a single line by
 * definition, so any rule that turns one line into two invents a row with the
 * wrong column count - which is exactly what a <br> hard break used to do.
 */
function tableRows(text) {
	let rows = 0;
	for (const line of lines(text)) {
		const trimmed = line.trim();
		if (trimmed.length > 0 && trimmed[0] === "|") rows += 1;
	}
	return rows;
}

/**
 * The lines inside every fenced code block, delimiters excluded, exactly as
 * written. This is deliberately a SECOND, independent implementation of the
 * module's fence scan - blockquote prefixes, indent up to a nested container,
 * matching marker character and run length, and a quoted fence ending with its
 * quote. If the module and this helper ever disagree, one of them is wrong.
 */
function fencedLines(text) {
	const kept = [];
	let open = null;
	for (const line of lines(text)) {
		const prefix = /^[ \t>]*/.exec(line)[0];
		const depth = (prefix.match(/>/g) ?? []).length;
		const indent = prefix.slice(prefix.lastIndexOf(">") + 1).replace(/\t/g, "    ").length;
		if (open !== null && open.depth > 0 && (line.trim() === "" || depth < open.depth)) {
			open = null;
		}
		const run = indent <= 12 ? /^(`{3,}|~{3,})(.*)$/.exec(line.slice(prefix.length)) : null;
		if (run === null) {
			if (open !== null) kept.push(line);
			continue;
		}
		if (open === null) {
			open = { depth, character: run[1][0], length: run[1].length };
		} else if (
			depth === open.depth &&
			run[1][0] === open.character &&
			run[1].length >= open.length &&
			run[2].trim() === ""
		) {
			open = null;
		} else {
			kept.push(line);
		}
	}
	return kept.join("\n");
}

test("fixture is present and covers every repaired construct", () => {
	assert.ok(corpus.vectors.length >= 90, "vector table shrank unexpectedly");
	assert.ok(corpus.messages.length >= 8, "production corpus shrank unexpectedly");
	for (const marker of ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "B1", "B2", "B3", "B4"]) {
		assert.ok(
			corpus.vectors.some((vector) => vector.name.startsWith(marker)),
			`no vectors for ${marker}`
		);
	}
});

for (const vector of corpus.vectors) {
	test(vector.name, () => {
		assert.equal(runVector(vector), vector.expected, vector.why);
	});
}

test("joinAssistantTextParts", () => {
	for (const vector of corpus.partVectors) {
		assert.equal(joinAssistantTextParts(vector.parts), vector.expected, vector.name);
	}
});

test("repairMarkdownBlocks preserves the blockquote run count of every vector", () => {
	for (const vector of corpus.vectors) {
		if (vector.fn !== "repairMarkdownBlocks" && vector.fn !== "normalizeAssistantMarkdown") {
			continue;
		}
		assert.equal(
			blockquoteRuns(runVector(vector)),
			blockquoteRuns(vector.input),
			`${vector.name}: a blockquote was split or merged`
		);
	}
});

test("no pipeline stage rewrites the contents of a fenced code block", () => {
	// A fence inside a blockquote or nested four columns in under a list used to
	// go untracked, and then EVERY stage edited its code: HTML deleted, bullet
	// glyphs rewritten, [FOLLOWUP] samples stripped, backticks appended.
	for (const vector of corpus.vectors) {
		assert.equal(
			fencedLines(runVector(vector)),
			fencedLines(vector.input),
			`${vector.name}: fenced code was rewritten`
		);
	}
	for (const message of corpus.messages) {
		for (const streaming of [false, true]) {
			assert.equal(
				fencedLines(normalizeAssistantMarkdown(message.content, { streaming })),
				fencedLines(message.content),
				`${message.id} streaming=${streaming}`
			);
		}
	}
});

test("no vector gains or loses a GFM table row", () => {
	for (const vector of corpus.vectors) {
		assert.equal(
			tableRows(runVector(vector)),
			tableRows(vector.input),
			`${vector.name}: a table row was split or merged`
		);
	}
});

test("normalizeAssistantMarkdown preserves the table row count of every production message", () => {
	for (const message of corpus.messages) {
		assert.equal(
			tableRows(normalizeAssistantMarkdown(message.content, { streaming: false })),
			tableRows(message.content),
			message.id
		);
	}
});

test("normalizeAssistantMarkdown preserves the blockquote run count of every production message", () => {
	for (const message of corpus.messages) {
		const before = blockquoteRuns(message.content);
		const after = blockquoteRuns(
			normalizeAssistantMarkdown(message.content, { streaming: false })
		);
		assert.equal(after, before, `${message.id} (${message.quirks.join(", ")})`);
	}
});

test("normalizeAssistantMarkdown is idempotent over the production corpus", () => {
	for (const message of corpus.messages) {
		for (const streaming of [false, true]) {
			const once = normalizeAssistantMarkdown(message.content, { streaming });
			const twice = normalizeAssistantMarkdown(once, { streaming });
			assert.equal(twice, once, `${message.id} streaming=${streaming}`);
		}
	}
});

test("normalizeAssistantMarkdown is idempotent over every vector", () => {
	for (const vector of corpus.vectors) {
		for (const streaming of [false, true]) {
			const once = normalizeAssistantMarkdown(vector.input, { streaming });
			const twice = normalizeAssistantMarkdown(once, { streaming });
			assert.equal(twice, once, `${vector.name} streaming=${streaming}`);
		}
	}
});

test("every prefix of every corpus entry survives being rendered mid-stream", () => {
	// A streamed answer is rendered at every intermediate length, so a rule that
	// only holds for whole messages is a rule that breaks on screen. 200 cut
	// points per entry, both stream modes: the normalizer must never throw, must
	// never turn one blockquote into two, and must be a fixed point.
	const entries = [
		...corpus.vectors.map((vector) => [vector.name, vector.input]),
		...corpus.messages.map((message) => [message.id, message.content]),
		...corpus.synthetic.map((vector) => [vector.name, vector.input]),
	];
	let checked = 0;
	for (const [name, text] of entries) {
		for (const cut of cutPositions(text.length, 200)) {
			const prefix = text.slice(0, cut);
			for (const streaming of [true, false]) {
				const where = `${name} cut=${cut} streaming=${streaming}`;
				let once;
				assert.doesNotThrow(() => {
					once = normalizeAssistantMarkdown(prefix, { streaming });
				}, where);
				assert.ok(
					blockquoteRuns(once) <= blockquoteRuns(prefix),
					`${where}: a blockquote was split`
				);
				assert.ok(
					tableRows(once) <= tableRows(prefix),
					`${where}: a table row was split`
				);
				assert.equal(
					normalizeAssistantMarkdown(once, { streaming }),
					once,
					`${where}: not a fixed point`
				);
				checked += 1;
			}
		}
	}
	assert.ok(checked > 5000, `sweep covered only ${checked} prefixes`);
});

test("no production message gains or loses a code fence", () => {
	for (const message of corpus.messages) {
		const fences = (text) => (text.match(/^ {0,3}(?:`{3,}|~{3,})/gm) ?? []).length;
		assert.equal(
			fences(normalizeAssistantMarkdown(message.content, { streaming: false })),
			fences(message.content),
			message.id
		);
	}
});

test("output never carries a stray carriage return", () => {
	for (const message of corpus.messages) {
		assert.ok(
			!normalizeAssistantMarkdown(message.content, { streaming: false }).includes("\r"),
			message.id
		);
	}
});

test("the web and Android copies of the module are byte-identical below the header", () => {
	// A plain `diff` cannot be the guard: the header comments differ by design,
	// and they already drifted once while the files claimed to be in sync.
	const bodyOf = (relativePath) => {
		const source = readFileSync(fileURLToPath(new URL(relativePath, import.meta.url)), "utf8");
		const headerEnd = source.indexOf("*/");
		assert.ok(headerEnd > 0, `${relativePath} has no leading block comment`);
		return source.slice(headerEnd + 2);
	};
	assert.equal(
		bodyOf("../mobile/src/lib/assistantMarkdown.ts"),
		bodyOf("../src/utils/assistantMarkdown.ts"),
		"src/utils/assistantMarkdown.ts and mobile/src/lib/assistantMarkdown.ts have diverged"
	);
});
