import { NextResponse } from "next/server";
import { getAuthUser } from "@/lib/auth";
import {
	getOrCreateDailyCrossAudio,
	readDailyCrossAudio,
	type DailyCrossAudio,
} from "@/lib/daily-cross-audio";

// POST does a model call plus a full ElevenLabs narration of a several-minute
// script, then a blob upload. 30-60s is normal.
export const maxDuration = 120;

function toResponse(audio: DailyCrossAudio) {
	return NextResponse.json({
		status: audio.status,
		url: audio.url,
		title: audio.title,
		script: audio.script,
		durationSec: audio.durationSec,
		generatedAt: audio.generatedAt,
	});
}

/**
 * The state of today's spoken devotional. Cheap and side-effect free: this is
 * what a client polls every few seconds while a generation it started is still
 * running. `status` is "unavailable" when this deployment has no ElevenLabs
 * key (the clients then render no Listen card at all), "none" when the user
 * has no day yet or has never asked for audio, "pending" while it is being
 * made, "ready" with a signed `url` good for 24 hours, or "failed".
 */
export async function GET(): Promise<Response> {
	try {
		const userId = await getAuthUser();
		return toResponse(await readDailyCrossAudio(userId));
	} catch (error) {
		return errorResponse(error);
	}
}

/**
 * Prepare today's spoken devotional, or return the one already prepared.
 *
 * Deliberately NOT pre-generated by the morning cron: every narration is billed
 * per character at ElevenLabs, and most users never tap play. Audio is made on
 * the first tap and reused for the rest of the day, so the cost follows actual
 * listening rather than the size of the user table.
 */
export async function POST(): Promise<Response> {
	try {
		const userId = await getAuthUser();
		return toResponse(await getOrCreateDailyCrossAudio(userId));
	} catch (error) {
		return errorResponse(error);
	}
}

function errorResponse(error: unknown): Response {
	if (error instanceof Response) return error;
	console.error("Error in verse-of-day/audio route:", error);
	return NextResponse.json(
		{ error: "Today's devotional audio could not be prepared." },
		{ status: 500 }
	);
}
