import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
	closeOpenInlineMarkdown,
	joinAssistantTextParts,
	normalizeAssistantMarkdown,
	normalizeInlineHtml,
	repairMarkdownBlocks,
	stripFollowUpMarkers,
} from "./assistantMarkdown";

// This file is deliberately ASCII-only and loops over the SAME fixture the web
// suite uses (tests/fixtures/assistant-markdown-corpus.json), so the two copies
// of the module are held to one vector table rather than two hand-mirrored
// ones. The fixture is generated by tests/fixtures/gen-assistant-markdown-corpus.mjs
// (run it to add or change a vector; it self-checks against the real module)
// because the editing tooling on this machine silently rewrites U+2014 to an
// ASCII hyphen, and a vector mangled that way passes for the wrong reason.

type Vector = {
	name: string;
	fn: string;
	input: string;
	streaming?: boolean;
	expected: string;
	why?: string;
};

type PartVector = { name: string; parts: string[]; expected: string };

type Message = { id: string; quirks: string[]; partial: boolean; content: string };

type SyntheticVector = { name: string; input: string; verdictBeforeTheFix: string };

type Corpus = {
	vectors: Vector[];
	partVectors: PartVector[];
	messages: Message[];
	synthetic: SyntheticVector[];
};

// .href rather than the URL object: Expo's TS lib pairs the DOM URL with
// node:url's parameter type, and the two are not assignable to each other.
const FIXTURE = fileURLToPath(
	new URL("../../../tests/fixtures/assistant-markdown-corpus.json", import.meta.url).href
);
const corpus = JSON.parse(readFileSync(FIXTURE, "utf8")) as Corpus;

const TEXT_ONLY: Record<string, (text: string) => string> = {
	closeOpenInlineMarkdown,
	normalizeInlineHtml,
	repairMarkdownBlocks,
};
const WITH_OPTIONS: Record<string, (text: string, options: { streaming: boolean }) => string> = {
	normalizeAssistantMarkdown,
	stripFollowUpMarkers,
};

function runVector(vector: Vector): string {
	const withOptions = WITH_OPTIONS[vector.fn];
	if (withOptions) return withOptions(vector.input, { streaming: vector.streaming === true });
	const textOnly = TEXT_ONLY[vector.fn];
	if (!textOnly) throw new Error(`unknown function in fixture: ${vector.fn}`);
	return textOnly(vector.input);
}

/** Up to `count` cut points spread evenly across a string of `length`. */
function cutPositions(length: number, count: number): number[] {
	if (length <= count) {
		const all: number[] = [];
		for (let index = 0; index <= length; index += 1) all.push(index);
		return all;
	}
	const positions: number[] = [];
	for (let index = 0; index < count; index += 1) {
		positions.push(Math.round((index * length) / (count - 1)));
	}
	return positions;
}

/**
 * Lines, counted the way markdown counts them. A lone CR is a line break to
 * every parser and to JS's own /m anchors, so a helper that split on "\n" alone
 * saw a CR-delimited document as one line and scored its invariants against a
 * shape no renderer ever sees.
 */
function lines(text: string): string[] {
	return text.replace(/\r\n?/g, "\n").split("\n");
}

/** Number of maximal runs of consecutive blockquote lines. */
function blockquoteRuns(text: string): number {
	let runs = 0;
	let inRun = false;
	for (const line of lines(text)) {
		const isQuote = /^ {0,3}>/.test(line);
		if (isQuote && !inRun) runs += 1;
		inRun = isQuote;
	}
	return runs;
}

/**
 * Lines that a GFM table would read as a row. A table row is a single line by
 * definition, so any rule that turns one line into two invents a row with the
 * wrong column count - which is exactly what a <br> hard break used to do.
 */
function tableRows(text: string): number {
	let rows = 0;
	for (const line of lines(text)) {
		const trimmed = line.trim();
		if (trimmed.length > 0 && trimmed[0] === "|") rows += 1;
	}
	return rows;
}

/**
 * The lines inside every fenced code block, delimiters excluded, exactly as
 * written. This is deliberately a SECOND, independent implementation of the
 * module's fence scan - blockquote prefixes, indent up to a nested container,
 * matching marker character and run length, and a quoted fence ending with its
 * quote. If the module and this helper ever disagree, one of them is wrong.
 */
function fencedLines(text: string): string {
	const kept: string[] = [];
	let open: { depth: number; character: string; length: number } | null = null;
	for (const line of lines(text)) {
		const prefix = /^[ \t>]*/.exec(line)?.[0] ?? "";
		const depth = (prefix.match(/>/g) ?? []).length;
		const indent = prefix.slice(prefix.lastIndexOf(">") + 1).replace(/\t/g, "    ").length;
		if (open !== null && open.depth > 0 && (line.trim() === "" || depth < open.depth)) {
			open = null;
		}
		const run = indent <= 12 ? /^(`{3,}|~{3,})(.*)$/.exec(line.slice(prefix.length)) : null;
		if (run === null) {
			if (open !== null) kept.push(line);
			continue;
		}
		if (open === null) {
			open = { depth, character: run[1][0], length: run[1].length };
		} else if (
			depth === open.depth &&
			run[1][0] === open.character &&
			run[1].length >= open.length &&
			run[2].trim() === ""
		) {
			open = null;
		} else {
			kept.push(line);
		}
	}
	return kept.join("\n");
}

describe("shared vector table", () => {
	it("is present and covers every repaired construct", () => {
		expect(corpus.vectors.length).toBeGreaterThanOrEqual(90);
		expect(corpus.messages.length).toBeGreaterThanOrEqual(8);
		for (const marker of ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "B1", "B2", "B3", "B4"]) {
			expect(corpus.vectors.some((vector) => vector.name.startsWith(marker))).toBe(true);
		}
	});

	for (const vector of corpus.vectors) {
		it(vector.name, () => {
			expect(runVector(vector)).toBe(vector.expected);
		});
	}

	it("joins assistant text parts", () => {
		for (const vector of corpus.partVectors) {
			expect(joinAssistantTextParts(vector.parts), vector.name).toBe(vector.expected);
		}
	});
});

describe("blockquote integrity", () => {
	it("preserves the blockquote run count of every vector", () => {
		for (const vector of corpus.vectors) {
			if (vector.fn !== "repairMarkdownBlocks" && vector.fn !== "normalizeAssistantMarkdown") {
				continue;
			}
			expect(blockquoteRuns(runVector(vector)), vector.name).toBe(
				blockquoteRuns(vector.input)
			);
		}
	});

	it("preserves the blockquote run count of every production message", () => {
		for (const message of corpus.messages) {
			expect(
				blockquoteRuns(normalizeAssistantMarkdown(message.content, { streaming: false })),
				`${message.id} (${message.quirks.join(", ")})`
			).toBe(blockquoteRuns(message.content));
		}
	});

	it("never splits a GFM table row", () => {
		for (const vector of corpus.vectors) {
			expect(tableRows(runVector(vector)), vector.name).toBe(tableRows(vector.input));
		}
		for (const message of corpus.messages) {
			expect(
				tableRows(normalizeAssistantMarkdown(message.content, { streaming: false })),
				message.id
			).toBe(tableRows(message.content));
		}
	});

	it("never rewrites the contents of a fenced code block", () => {
		// A fence inside a blockquote or nested four columns in under a list used
		// to go untracked, and then EVERY stage edited its code: HTML deleted,
		// bullet glyphs rewritten, [FOLLOWUP] samples stripped, backticks appended.
		for (const vector of corpus.vectors) {
			expect(fencedLines(runVector(vector)), vector.name).toBe(fencedLines(vector.input));
		}
		for (const message of corpus.messages) {
			for (const streaming of [false, true]) {
				expect(
					fencedLines(normalizeAssistantMarkdown(message.content, { streaming })),
					`${message.id} streaming=${streaming}`
				).toBe(fencedLines(message.content));
			}
		}
	});

	it("never leaves a stray carriage return", () => {
		for (const message of corpus.messages) {
			expect(
				normalizeAssistantMarkdown(message.content, { streaming: false }).includes("\r"),
				message.id
			).toBe(false);
		}
	});
});

describe("idempotence", () => {
	it("holds over the production corpus", () => {
		for (const message of corpus.messages) {
			for (const streaming of [false, true]) {
				const once = normalizeAssistantMarkdown(message.content, { streaming });
				expect(
					normalizeAssistantMarkdown(once, { streaming }),
					`${message.id} streaming=${streaming}`
				).toBe(once);
			}
		}
	});

	it("holds over every vector", () => {
		for (const vector of corpus.vectors) {
			for (const streaming of [false, true]) {
				const once = normalizeAssistantMarkdown(vector.input, { streaming });
				expect(
					normalizeAssistantMarkdown(once, { streaming }),
					`${vector.name} streaming=${streaming}`
				).toBe(once);
			}
		}
	});
});

describe("stream-cut sweep", () => {
	it("survives every prefix of every corpus entry", () => {
		// A streamed answer is rendered at every intermediate length, so a rule
		// that only holds for whole messages is a rule that breaks on screen. 200
		// cut points per entry, both stream modes: the normalizer must never
		// throw, must never turn one blockquote into two, and must be a fixed
		// point.
		const entries: [string, string][] = [
			...corpus.vectors.map((vector): [string, string] => [vector.name, vector.input]),
			...corpus.messages.map((message): [string, string] => [message.id, message.content]),
			...corpus.synthetic.map((vector): [string, string] => [vector.name, vector.input]),
		];
		let checked = 0;
		for (const [name, text] of entries) {
			for (const cut of cutPositions(text.length, 200)) {
				const prefix = text.slice(0, cut);
				for (const streaming of [true, false]) {
					const where = `${name} cut=${cut} streaming=${streaming}`;
					const once = normalizeAssistantMarkdown(prefix, { streaming });
					expect(blockquoteRuns(once), `${where}: a blockquote was split`).toBeLessThanOrEqual(
						blockquoteRuns(prefix)
					);
					expect(tableRows(once), `${where}: a table row was split`).toBeLessThanOrEqual(
						tableRows(prefix)
					);
					expect(
						normalizeAssistantMarkdown(once, { streaming }),
						`${where}: not a fixed point`
					).toBe(once);
					checked += 1;
				}
			}
		}
		expect(checked).toBeGreaterThan(5000);
	});
});

describe("copy sync", () => {
	it("keeps the web and Android modules byte-identical below the header", () => {
		// A plain `diff` cannot be the guard: the header comments differ by
		// design, and they already drifted once while the files claimed to be in
		// sync.
		const bodyOf = (relativePath: string): string => {
			const source = readFileSync(
				fileURLToPath(new URL(relativePath, import.meta.url).href),
				"utf8"
			);
			const headerEnd = source.indexOf("*/");
			expect(headerEnd, `${relativePath} has no leading block comment`).toBeGreaterThan(0);
			return source.slice(headerEnd + 2);
		};
		expect(bodyOf("./assistantMarkdown.ts")).toBe(
			bodyOf("../../../src/utils/assistantMarkdown.ts")
		);
	});
});
